# Generated by Django 5.2.4 on 2025-09-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(max_length=100, verbose_name="场站名称"),
                ),
                (
                    "unit_config",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="机组配置"
                    ),
                ),
                (
                    "installed_capacity",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="装机容量"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                (
                    "area_km2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="面积(平方公里)"
                    ),
                ),
                (
                    "ultra_short_term_rule",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="超短期规则"
                    ),
                ),
                (
                    "day_ahead_rule",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="日前规则"
                    ),
                ),
                (
                    "mid_long_term_rule",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="中长期规则"
                    ),
                ),
                (
                    "csv_path",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="csv文件路径",
                    ),
                ),
            ],
            options={
                "db_table": "power_station",
                "managed": False,
            },
        ),
    ]
