# Generated by Django 5.2.4 on 2025-09-26 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("list_tables", "0002_apilog_forecasttype_forecasttask_windfarmdata_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="station",
            options={"managed": True},
        ),
    ]
