# Generated by Django 5.2.4 on 2025-10-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list_tables", "0003_alter_station_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.IntegerField()),
                ("timeStamp", models.DateTimeField()),
                ("power", models.FloatField(blank=True, null=True)),
                ("windSpeed", models.FloatField(blank=True, null=True)),
                ("windDirection", models.FloatField(blank=True, null=True)),
                ("airPressure", models.FloatField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("windDirection_sin", models.FloatField(blank=True, null=True)),
                ("windDirection_cos", models.FloatField(blank=True, null=True)),
                ("windSpeed_pre_1", models.FloatField(blank=True, null=True)),
                ("windSpeed_pre_2", models.FloatField(blank=True, null=True)),
                ("windSpeed_post_1", models.FloatField(blank=True, null=True)),
                ("windSpeed_post_2", models.FloatField(blank=True, null=True)),
                ("fValue", models.FloatField(blank=True, null=True)),
                ("windSpeed_center", models.FloatField(blank=True, null=True)),
                ("windSpeed_spread", models.FloatField(blank=True, null=True)),
                ("windSpeed_height", models.FloatField(blank=True, null=True)),
                ("windSpeed_max_change", models.FloatField(blank=True, null=True)),
                ("windSpeed_avg_change", models.FloatField(blank=True, null=True)),
                ("windSpeed_rising_strength", models.FloatField(blank=True, null=True)),
                (
                    "windSpeed_falling_strength",
                    models.FloatField(blank=True, null=True),
                ),
                ("windSpeed_volatility", models.FloatField(blank=True, null=True)),
                ("month_sin", models.FloatField(blank=True, null=True)),
                ("month_cos", models.FloatField(blank=True, null=True)),
                ("two_days_ago_avg_power", models.FloatField(blank=True, null=True)),
                ("two_days_ago_max_power", models.FloatField(blank=True, null=True)),
                ("two_days_ago_min_power", models.FloatField(blank=True, null=True)),
                ("one_day_ago_morning_avg", models.FloatField(blank=True, null=True)),
                ("one_day_ago_morning_max", models.FloatField(blank=True, null=True)),
                ("one_day_ago_morning_min", models.FloatField(blank=True, null=True)),
                ("two_days_ago_power", models.FloatField(blank=True, null=True)),
                ("hour", models.FloatField(blank=True, null=True)),
                ("swdown", models.FloatField(blank=True, null=True)),
                ("glw", models.FloatField(blank=True, null=True)),
                ("swddni", models.FloatField(blank=True, null=True)),
                ("swddir", models.FloatField(blank=True, null=True)),
                ("swddif", models.FloatField(blank=True, null=True)),
                ("td2m", models.FloatField(blank=True, null=True)),
                ("tsd", models.FloatField(blank=True, null=True)),
                ("dpt2m", models.FloatField(blank=True, null=True)),
                ("psfc", models.FloatField(blank=True, null=True)),
                ("rh2m", models.FloatField(blank=True, null=True)),
                ("qv2m", models.FloatField(blank=True, null=True)),
                ("clflo", models.FloatField(blank=True, null=True)),
                ("clfhi", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
