# Generated by Django 5.2.6 on 2025-10-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list_tables", "0004_task_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task_data",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
