# Generated by Django 5.2.6 on 2025-10-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list_tables", "0005_alter_task_data_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task_data",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
