# Generated by Django 5.2.4 on 2025-10-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list_tables", "0006_alter_task_data_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task_data",
            name="wdir",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task_data",
            name="wspd",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
