# Generated by Django 4.2.1 on 2025-07-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='场站名称')),
                ('install_capacity', models.CharField(max_length=100, verbose_name='装机容量')),
                ('total_capacity', models.CharField(max_length=100, verbose_name='总容量')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('latitude_id', models.IntegerField(verbose_name='纬度编号')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('longitude_id', models.FloatField(verbose_name='经度编号')),
                ('forecast_4h', models.CharField(max_length=200, verbose_name='4小时预测')),
                ('forecast_24h', models.CharField(max_length=200, verbose_name='24小时预测')),
                ('forecast_7d', models.CharField(max_length=200, verbose_name='7天预测')),
            ],
        ),
    ]
